// filename: product-detail.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, DestroyRef, OnInit, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { catchError, map, of, switchMap } from 'rxjs';
import { Product, ProductResponse, Review } from '../../core/models/product.model';
import { ProductService } from '../../services/product.service';
import { UserListsService } from '../../services/user-lists.service';

@Component({
  selector: 'app-product-detail',
  standalone: true,
  imports: [CurrencyPipe, DatePipe, RouterLink],
  templateUrl: './product-detail.html',
})
export class ProductDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private productService = inject(ProductService);
  private destroyRef = inject(DestroyRef);

  lists = inject(UserListsService);
  product = signal<Product | null>(null);
  reviews = signal<Review[]>([]);
  loading = signal(true);
  error = signal<string | null>(null);

  ngOnInit(): void {
    this.lists.loadAll();
    this.route.paramMap.pipe(
      map((params) => Number(params.get('id'))),
      switchMap((id) => !Number.isInteger(id) || id <= 0
        ? of<ProductResponse | null>(null)
        : this.productService.getProductById(id).pipe(catchError(() => of<ProductResponse | null>(null)))),
      takeUntilDestroyed(this.destroyRef)
    ).subscribe((response) => {
      if (!response?.product) {
        this.error.set('Unable to load product details');
        this.loading.set(false);
        return;
      }
      this.product.set(response.product);
      this.reviews.set(response.product.reviews ?? []);
      this.loading.set(false);
    });
  }

  addToCart(): void {
    const product = this.product();
    if (product) this.lists.addToCart(product, 1);
  }

  toggleWishlist(): void {
    const product = this.product();
    if (product) this.lists.toggleWishlist(product);
  }
}
