// filename: app.routes.server.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  // AUTH — no SEO needed, stay CSR
  { path: 'login',          renderMode: RenderMode.Client },
  { path: 'signup',         renderMode: RenderMode.Client },

  // PUBLIC — candidate for SSR later (SEO benefit)
  { path: 'about',          renderMode: RenderMode.Client },

  // PROTECTED — always CSR (auth-gated, no SEO value)
  { path: 'home',           renderMode: RenderMode.Client },
  { path: 'products/:id',   renderMode: RenderMode.Client }, // ← flip to Server later
  { path: 'cart',           renderMode: RenderMode.Client },
  { path: 'wishlist',       renderMode: RenderMode.Client },
  { path: 'checkout',       renderMode: RenderMode.Client },
  { path: 'payment-status', renderMode: RenderMode.Client },
  { path: 'orders',         renderMode: RenderMode.Client },

  // FALLBACK
  { path: '**',             renderMode: RenderMode.Client },
];
