// filename: app.spec.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { provideMockStore } from '@ngrx/store/testing';
import { App } from './app';

describe('App', () => {

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [App, RouterTestingModule],
      providers: [
        // ✅ Same fix — AppComponent also needs Store provided
        provideMockStore({ initialState: {} }),
      ],
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(App);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  // ✅ FIX: removed the outdated 'Hello, shop-app' test
  // That was auto-generated by Angular CLI — it no longer applies
  // to your real app which has its own routing and components
  it('should have router outlet in template', () => {
    const fixture = TestBed.createComponent(App);
    fixture.detectChanges();
    const el: HTMLElement = fixture.nativeElement;
    // app.component just holds the router outlet — verify it exists
    expect(el.querySelector('router-outlet')).not.toBeNull();
  });

});
