// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: app.routes.ts

import { Routes } from '@angular/router';
import { authGuard } from './core/auth/guards/auth-guard';
import { Login } from './features/auth/login/login';
import { Signup } from './features/auth/signup/signup';
import { Home } from './features/home/home/home';
import { ProductDetailComponent } from './shared/product-detail/product-detail';
import { CartComponent } from './features/home/cart/cart';
import { WishlistComponent } from './features/home/wishlist/wishlist';
import { CheckoutComponent } from './features/home/checkout/checkout';
import { PaymentStatusComponent } from './features/home/payment-status/payment-status';
import { OrdersComponent } from './features/home/orders/orders';
import { AboutComponent } from './features/home/about/about';

export const routes: Routes = [
  { path: 'login', component: Login },
  { path: 'signup', component: Signup },
  { path: 'about', component: AboutComponent },

  { path: 'home', component: Home, canActivate: [authGuard] },
  { path: 'products/:id', component: ProductDetailComponent, canActivate: [authGuard] },
  { path: 'cart', component: CartComponent, canActivate: [authGuard] },
  { path: 'wishlist', component: WishlistComponent, canActivate: [authGuard] },
  { path: 'checkout', component: CheckoutComponent, canActivate: [authGuard] },
  { path: 'payment-status', component: PaymentStatusComponent, canActivate: [authGuard] },
  { path: 'orders', component: OrdersComponent, canActivate: [authGuard] },

  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: '**', redirectTo: 'home' },
];
