// filename: cart.routes.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const express     = require('express');
const { getDb }   = require('../db');
const verifyToken = require('../middleware/verifyToken');

const router = express.Router();
router.use(verifyToken);

const toPositiveInt = (value, fallback = 1) => {
  const n = Number(value);
  return Number.isInteger(n) && n > 0 ? n : fallback;
};

// GET /:userId
router.get('/:userId', async (req, res) => {
  try {
    const userId = req.params.userId;
    if (!userId) return res.status(400).json({ success: false, message: 'userId is required' });

    const cart = await getDb().collection('carts').findOne({ userId });
    return res.json({ success: true, items: cart?.items ?? [] });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to fetch cart', error: error.message });
  }
});

// POST /:userId
router.post('/:userId', async (req, res) => {
  try {
    const db        = getDb();
    const userId    = req.params.userId;
    const productId = Number(req.body.productId);
    const quantity  = toPositiveInt(req.body.quantity, 1);

    if (!userId || Number.isNaN(productId))
      return res.status(400).json({ success: false, message: 'Invalid request' });

    const product = await db.collection('products').findOne({ id: productId });
    if (!product) return res.status(404).json({ success: false, message: 'Product not found' });

    const cartCollection = db.collection('carts');
    const cart = (await cartCollection.findOne({ userId })) ?? { userId, items: [] };

    const existing = cart.items.find((item) => item.productId === productId);
    if (existing) {
      existing.quantity += quantity;
    } else {
      cart.items.push({
        productId: product.id,
        quantity,
        name:      product.title || product.name,
        price:     product.price,
        thumbnail: product.image || product.thumbnail,
        brand:     product.brand || '',
        stock:     product.stock,
      });
    }

    await cartCollection.updateOne(
      { userId },
      { $set: { userId, items: cart.items, updatedAt: new Date() } },
      { upsert: true }
    );

    return res.json({ success: true, message: 'Cart updated', items: cart.items });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to add to cart', error: error.message });
  }
});

// PATCH /:userId/:productId
router.patch('/:userId/:productId', async (req, res) => {
  try {
    const db        = getDb();
    const userId    = req.params.userId;
    const productId = Number(req.params.productId);
    const quantity  = Number(req.body.quantity);

    if (!userId || Number.isNaN(productId) || !Number.isInteger(quantity))
      return res.status(400).json({ success: false, message: 'Invalid request' });

    const cartCollection = db.collection('carts');
    const cart = (await cartCollection.findOne({ userId })) ?? { userId, items: [] };

    cart.items = quantity <= 0
      ? cart.items.filter((item) => item.productId !== productId)
      : cart.items.map((item) => item.productId === productId ? { ...item, quantity } : item);

    await cartCollection.updateOne(
      { userId },
      { $set: { userId, items: cart.items, updatedAt: new Date() } },
      { upsert: true }
    );

    return res.json({ success: true, message: 'Cart updated', items: cart.items });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to update cart', error: error.message });
  }
});

// DELETE /:userId — clear entire cart
router.delete('/:userId', async (req, res) => {
  try {
    const userId = req.params.userId;
    if (!userId) return res.status(400).json({ success: false, message: 'userId is required' });

    await getDb().collection('carts').updateOne(
      { userId },
      { $set: { items: [], updatedAt: new Date() } }
    );

    return res.json({ success: true, items: [] });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to clear cart', error: error.message });
  }
});

// DELETE /:userId/:productId — remove single item
router.delete('/:userId/:productId', async (req, res) => {
  try {
    const userId    = req.params.userId;
    const productId = Number(req.params.productId);

    if (!userId || Number.isNaN(productId))
      return res.status(400).json({ success: false, message: 'Invalid request' });

    const cartCollection = getDb().collection('carts');
    const cart = (await cartCollection.findOne({ userId })) ?? { userId, items: [] };
    cart.items = cart.items.filter((item) => item.productId !== productId);

    await cartCollection.updateOne(
      { userId },
      { $set: { userId, items: cart.items, updatedAt: new Date() } },
      { upsert: true }
    );

    return res.json({ success: true, message: 'Item removed', items: cart.items });
  } catch (error) {
    return res.status(500).json({ success: false, message: 'Failed to remove item', error: error.message });
  }
});

module.exports = router;
