// filename: payment.routes.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const express     = require('express');
const { getDb }   = require('../db');
const verifyToken = require('../middleware/verifyToken');

const router = express.Router();

// ✅ No top-level Stripe init — lazy only
const getStripe = () => {
  const key = process.env.STRIPE_SECRET_KEY;
  if (!key) throw new Error('STRIPE_SECRET_KEY is not set in .env');
  return require('stripe')(key);
};

const getWebhookSecret = () => {
  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  if (!secret) throw new Error('STRIPE_WEBHOOK_SECRET is not set in .env');
  return secret;
};

// ── POST /api/payments/create-intent ─────────────────────────
router.post('/create-intent', verifyToken, async (req, res) => {
  try {
    const stripe  = getStripe();
    const { amount, items } = req.body;
    const userId  = req.userId || 'anonymous';
    const email   = req.currentUser?.email || 'guest@eshopper.com';

    if (!amount || amount <= 0)
      return res.status(400).json({ success: false, message: 'Invalid amount' });

    const paymentIntent = await stripe.paymentIntents.create({
      amount:               Math.round(amount * 100),
      currency:             'usd',
      receipt_email:        email,
      payment_method_types: ['card'],
      metadata: {
        userId,
        email,
        items: JSON.stringify(items ?? []),
      },
    });

    return res.status(200).json({
      success:      true,
      clientSecret: paymentIntent.client_secret,
    });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
});

// ── POST /api/payments/webhook ────────────────────────────────
router.post(
  '/webhook',
  express.raw({ type: 'application/json' }),
  async (req, res) => {
    const sig = req.headers['stripe-signature'];
    let event;

    try {
      event = getStripe().webhooks.constructEvent(
        req.body, sig, getWebhookSecret()
      );
    } catch (err) {
      console.error('[Webhook] Signature failed:', err.message);
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }

    if (event.type === 'payment_intent.succeeded') {
      const intent = event.data.object;
      try {
        await getDb().collection('orders').insertOne({
          paymentIntentId: intent.id,
          amount:          intent.amount / 100,
          currency:        intent.currency,
          userId:          intent.metadata?.userId || '',
          email:           intent.receipt_email || intent.metadata?.email,
          items:           JSON.parse(intent.metadata?.items || '[]'),
          status:          'paid',
          createdAt:       new Date(),
        });
        console.log('[Webhook] Order saved:', intent.id);
      } catch (err) {
        console.error('[Webhook] DB insert failed:', err.message);
      }
    }

    return res.json({ received: true });
  }
);

module.exports = router;
