// filename: server.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const path = require('path');
const fs   = require('fs');

require('dotenv').config({ path: path.join(__dirname, '.env'), override: true });

const express        = require('express');
const cors           = require('cors');
const { connectToDatabase } = require('./db');

const productsRoutes = require('./routes/products.routes');
const usersRoutes    = require('./routes/users.routes');
const cartRoutes     = require('./routes/cart.routes');
const wishlistRoutes = require('./routes/wishlist.routes');
const paymentRoutes  = require('./routes/payment.routes');
const orderRoutes    = require('./routes/order.routes');

const app = express();

// ── Middleware ────────────────────────────────────────────────
app.use(cors({
  origin: process.env.FRONTEND_URL || '*',
  credentials: true
}));
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());

// ── API Routes ────────────────────────────────────────────────
app.use('/api/products',  productsRoutes);
app.use('/api/users',     usersRoutes);
app.use('/api/cart',      cartRoutes);
app.use('/api/wishlist',  wishlistRoutes);
app.use('/api/payments',  paymentRoutes);
app.use('/api/orders',    orderRoutes);

// ── Serve Angular CSR ─────────────────────────────────────────
const browserPath = path.join(__dirname, '../frontend/dist/shop-app/browser');
const rootPath    = path.join(__dirname, '../frontend/dist/shop-app');

const staticPath  = fs.existsSync(path.join(browserPath, 'index.html'))
  ? browserPath
  : rootPath;

console.log(`✅ Serving static files from: ${staticPath}`);

// serve static assets (js, css, images)
app.use(express.static(staticPath));

// ── Catch-All: send index.html for ALL non-API routes ─────────
app.use((req, res, next) => {
  if (req.path.startsWith('/api/')) return next();
  const indexFile = path.join(staticPath, 'index.html');
  if (!fs.existsSync(indexFile)) {
    return res.status(404).send('index.html not found');
  }
  res.sendFile(indexFile);
});

// ── 404 handler for unmatched API routes ─────────────────────
app.use((req, res) => {
  res.status(404).json({ error: 'API route not found' });
});

// ── Start ─────────────────────────────────────────────────────
connectToDatabase()
  .then(() => {
    const port = process.env.PORT || 3000;
    app.listen(port, () => console.log(`✅ Server running on port ${port}`));
  })
  .catch((err) => {
    console.error('MongoDB connection failed:', err);
    process.exit(1);
  });
