// filename: server.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const path = require('path');
const fs   = require('fs');

require('dotenv').config({ path: path.join(__dirname, '.env'), override: true });

const express        = require('express');
const cors           = require('cors');
const { connectToDatabase } = require('./db');

const productsRoutes = require('./routes/products.routes');
const usersRoutes    = require('./routes/users.routes');
const cartRoutes     = require('./routes/cart.routes');
const wishlistRoutes = require('./routes/wishlist.routes');
const paymentRoutes  = require('./routes/payment.routes');
const orderRoutes    = require('./routes/order.routes');

const app = express();

// ── Resolve static path ───────────────────────────────────────
const possiblePaths = [
  path.join(__dirname, '../frontend/dist/shop-app/browser'),
  path.join(__dirname, '../frontend/dist/shop-app'),
  path.join(__dirname, '../../frontend/dist/shop-app/browser'),
  path.join(__dirname, '../../frontend/dist/shop-app'),
];

let staticPath = null;
for (const p of possiblePaths) {
  if (fs.existsSync(path.join(p, 'index.html'))) {
    staticPath = p;
    break;
  }
}

if (!staticPath) {
  console.error('❌ index.html NOT FOUND. Searched:');
  possiblePaths.forEach(p => console.error('  ', p));
} else {
  console.log(`✅ Serving static files from: ${staticPath}`);
}

// ── Middleware ────────────────────────────────────────────────
app.use(cors({ origin: process.env.FRONTEND_URL || '*', credentials: true }));
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());

// ── API Routes ────────────────────────────────────────────────
app.use('/api/products',  productsRoutes);
app.use('/api/users',     usersRoutes);
app.use('/api/cart',      cartRoutes);
app.use('/api/wishlist',  wishlistRoutes);
app.use('/api/payments',  paymentRoutes);
app.use('/api/orders',    orderRoutes);

// ── Serve Angular Static Files ────────────────────────────────
if (staticPath) {
  app.use(express.static(staticPath));
}

// ── Catch-All ─────────────────────────────────────────────────
// ✅ Use regex instead of '*' — works with Node 26 + path-to-regexp v8
app.get(/(.*)/, (req, res) => {
  if (req.path.startsWith('/api/')) {
    return res.status(404).json({ error: 'API route not found' });
  }

  if (!staticPath) {
    return res.status(500).send(
      `index.html not found. Searched: ${possiblePaths.join(', ')}`
    );
  }

  res.sendFile(path.join(staticPath, 'index.html'), (err) => {
    if (err) {
      console.error('sendFile error:', err);
      res.status(500).send(`Failed to send index.html: ${err.message}`);
    }
  });
});

// ── Start ─────────────────────────────────────────────────────
connectToDatabase()
  .then(() => {
    const port = process.env.PORT || 3000;
    app.listen(port, () => console.log(`✅ Server running on port ${port}`));
  })
  .catch((err) => {
    console.error('MongoDB connection failed:', err);
    process.exit(1);
  });
