// filename: server.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const path           = require('path');
const fs             = require('fs');
const { pathToFileURL } = require('url');   // ✅ NEW

require('dotenv').config({
  path: path.join(__dirname, '.env'),
  override: true,
});

const express        = require('express');
const cors           = require('cors');
const { connectToDatabase } = require('./db');

const productsRoutes = require('./routes/products.routes');
const usersRoutes    = require('./routes/users.routes');
const cartRoutes     = require('./routes/cart.routes');
const wishlistRoutes = require('./routes/wishlist.routes');
const paymentRoutes  = require('./routes/payment.routes');
const orderRoutes    = require('./routes/order.routes');

const app = express();

// ── Middleware ────────────────────────────────────────────────
app.use(cors());
app.use('/api/payments/webhook', express.raw({ type: 'application/json' }));
app.use(express.json());

// ── API Routes ────────────────────────────────────────────────
app.use('/api/products',  productsRoutes);
app.use('/api/users',     usersRoutes);
app.use('/api/cart',      cartRoutes);
app.use('/api/wishlist',  wishlistRoutes);
app.use('/api/payments',  paymentRoutes);
app.use('/api/orders',    orderRoutes);

// ── Angular SSR ───────────────────────────────────────────────
const ssrServer = path.join(__dirname, '../frontend/dist/shop-app/server/server.mjs');

if (fs.existsSync(ssrServer)) {
  import(pathToFileURL(ssrServer).href)   // ✅ file:///C:/... format
    .then(({ reqHandler }) => {
      app.use(reqHandler);
      console.log('✅ Angular SSR handler mounted');
    })
    .catch((err) => console.error('SSR mount failed:', err));
} else {
  console.log('⚠️  Angular dist not found — API-only mode');
}

// ── Start ─────────────────────────────────────────────────────
connectToDatabase()
  .then(() => {
    const port = process.env.PORT || 3000;
    app.listen(port, () => console.log(`✅ Server running on port ${port}`));
  })
  .catch((err) => {
    console.error('MongoDB connection failed:', err);
    process.exit(1);
  });
