// filename: products.selectors.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { createSelector } from '@ngrx/store';
import { productsFeature } from './products.reducer';

export const {
  selectProducts,
  selectCategories: selectCategoriesState,
  selectLoading:           selectProductsLoading,
  selectLoadingMore,                              // ← new
  selectCategoriesLoading,
  selectError:             selectProductsError,
  selectCategoriesError,
  selectSearchTerm,
  selectActiveCategory,
  selectSortBy,
  selectPage,
  selectPageSize,
  selectTotal,
} = productsFeature;

export const selectCategories = createSelector(
  selectCategoriesState,
  (cats) => ['All', ...cats.filter((c) => c !== 'All')]
);

export const selectTotalPages = createSelector(
  selectTotal, selectPageSize,
  (total, pageSize) => Math.max(1, Math.ceil(total / pageSize))
);

// ← true when there are still more products to load
export const selectHasMore = createSelector(
  selectProducts, selectTotal,
  (products, total) => products.length < total
);
