// filename: products.actions.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { createActionGroup, emptyProps, props } from '@ngrx/store';
import { Product } from '../../core/models/product.model';

export const ProductsActions = createActionGroup({
  source: 'Products',
  events: {

    // ── Initial load (replaces product list) ──────────────────────
    'Load Products':         emptyProps(),
    'Load Products Success': props<{ products: Product[]; total: number; page: number; pageSize: number }>(),
    'Load Products Failure': props<{ error: string }>(),

    // ── Infinite scroll (appends to product list) ─────────────────
    'Load More Products':         emptyProps(),
    'Append Products Success':    props<{ products: Product[]; total: number; page: number; pageSize: number }>(),
    'Append Products Failure':    props<{ error: string }>(),

    // ── Categories ────────────────────────────────────────────────
    'Load Categories':         emptyProps(),
    'Load Categories Success': props<{ categories: string[] }>(),
    'Load Categories Failure': props<{ error: string }>(),

    // ── Filters (each resets page + clears product list) ──────────
    'Set Search Term': props<{ searchTerm: string }>(),
    'Set Category':    props<{ category: string }>(),
    'Set Sort':        props<{ sortBy: 'price-asc' | 'price-desc' }>(),
    'Set Page':        props<{ page: number }>(),
  },
});
