// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: products.selectors.ts
import { createSelector } from '@ngrx/store';
import { productsFeature } from './products.reducer';

export const {
  selectProducts,
  selectCategories: selectCategoriesState,
  selectLoading: selectProductsLoading,
  selectCategoriesLoading,
  selectError: selectProductsError,
  selectCategoriesError,
  selectSearchTerm,
  selectActiveCategory,
  selectSortBy,
  selectPage,
  selectPageSize,
  selectTotal,
} = productsFeature;

export const selectCategories = createSelector(
  selectCategoriesState,
  (categories) => ['All', ...categories.filter((category) => category !== 'All')]
);

export const selectTotalPages = createSelector(
  selectTotal,
  selectPageSize,
  (total, pageSize) => Math.max(1, Math.ceil(total / pageSize))
);
