// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: products.reducer.ts
import { createFeature, createReducer, on } from '@ngrx/store';
import { Product } from '../../core/models/product.model';
import { ProductsActions } from './products.actions';

export interface ProductsState {
  products: Product[];
  categories: string[];
  loading: boolean;
  categoriesLoading: boolean;
  error: string | null;
  categoriesError: string | null;
  searchTerm: string;
  activeCategory: string;
  sortBy: 'price-asc' | 'price-desc';
  page: number;
  pageSize: number;
  total: number;
}

const initialState: ProductsState = {
  products: [],
  categories: [],
  loading: false,
  categoriesLoading: false,
  error: null,
  categoriesError: null,
  searchTerm: '',
  activeCategory: 'All',
  sortBy: 'price-asc',
  page: 1,
  pageSize: 8,
  total: 0,
};

export const productsFeature = createFeature({
  name: 'products',
  reducer: createReducer(
    initialState,

    on(ProductsActions.setSearchTerm, (state, { searchTerm }) => ({
      ...state,
      searchTerm,
      page: 1,
    })),

    on(ProductsActions.setCategory, (state, { category }) => ({
      ...state,
      activeCategory: category,
      page: 1,
    })),

    on(ProductsActions.setSort, (state, { sortBy }) => ({
      ...state,
      sortBy,
      page: 1,
    })),

    on(ProductsActions.setPage, (state, { page }) => ({
      ...state,
      page,
    })),

    on(ProductsActions.loadProducts, (state) => ({
      ...state,
      loading: true,
      error: null,
    })),

    on(ProductsActions.loadProductsSuccess, (state, { products, total, page, pageSize }) => ({
      ...state,
      products,
      total,
      page,
      pageSize,
      loading: false,
    })),

    on(ProductsActions.loadProductsFailure, (state, { error }) => ({
      ...state,
      loading: false,
      error,
    })),

    on(ProductsActions.loadCategories, (state) => ({
      ...state,
      categoriesLoading: true,
      categoriesError: null,
    })),

    on(ProductsActions.loadCategoriesSuccess, (state, { categories }) => ({
      ...state,
      categories: categories.filter(Boolean),
      categoriesLoading: false,
    })),

    on(ProductsActions.loadCategoriesFailure, (state, { error }) => ({
      ...state,
      categoriesLoading: false,
      categoriesError: error,
    }))
  ),
});
