// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: products.effects.ts
import { Injectable, inject } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { concatLatestFrom } from '@ngrx/operators';
import { Store } from '@ngrx/store';
import { catchError, debounceTime, map, of, switchMap } from 'rxjs';
import { ProductService } from '../../services/product.service';
import { ProductsActions } from './products.actions';
import {
  selectActiveCategory,
  selectPage,
  selectPageSize,
  selectSearchTerm,
  selectSortBy,
} from './products.selectors';

@Injectable()
export class ProductsEffects {
  private actions$ = inject(Actions);
  private store = inject(Store);
  private productService = inject(ProductService);

  searchChange$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductsActions.setSearchTerm),
      debounceTime(300),
      map(() => ProductsActions.loadProducts())
    )
  );

  queryChange$ = createEffect(() =>
    this.actions$.pipe(
      ofType(
        ProductsActions.setCategory,
        ProductsActions.setSort,
        ProductsActions.setPage
      ),
      map(() => ProductsActions.loadProducts())
    )
  );

  loadCategories$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductsActions.loadCategories),
      switchMap(() =>
        this.productService.getCategories().pipe(
          map((response) =>
            ProductsActions.loadCategoriesSuccess({
              categories: response.categories ?? [],
            })
          ),
          catchError(() =>
            of(
              ProductsActions.loadCategoriesFailure({
                error: 'Failed to load categories',
              })
            )
          )
        )
      )
    )
  );

  loadProducts$ = createEffect(() =>
    this.actions$.pipe(
      ofType(ProductsActions.loadProducts),
      concatLatestFrom(() => [
        this.store.select(selectSearchTerm),
        this.store.select(selectActiveCategory),
        this.store.select(selectSortBy),
        this.store.select(selectPage),
        this.store.select(selectPageSize),
      ]),
      switchMap(([, searchTerm, activeCategory, sortBy, page, pageSize]) =>
        this.productService
          .getProducts({
            search: searchTerm,
            category: activeCategory === 'All' ? undefined : activeCategory,
            sort: sortBy,
            page,
            pageSize,
          })
          .pipe(
            map((response) =>
              ProductsActions.loadProductsSuccess({
                products: response.products ?? [],
                total: response.total ?? 0,
                page: response.page ?? page,
                pageSize: response.pageSize ?? pageSize,
              })
            ),
            catchError(() =>
              of(
                ProductsActions.loadProductsFailure({
                  error: 'Failed to load products',
                })
              )
            )
          )
      )
    )
  );
}
