// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: payment-status.ts

import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Header } from '../../../shared/header/header';
import { UserListsService } from '../../../services/user-lists.service';
import { Footer } from '../../../shared/footer/footer';

@Component({
  selector: 'app-payment-status',
  standalone: true,
  imports: [Header, RouterLink, Footer],
  templateUrl: './payment-status.html',
})
export class PaymentStatusComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private lists = inject(UserListsService);

  status = '';

  ngOnInit(): void {
    this.status = this.route.snapshot.queryParams['status'] ?? 'unknown';

    // Clear cart locally on success (backend already saved the order via webhook)
    if (this.status === 'success') {
      this.lists.clearCart();   
    }
  }
}
