// filename: backend/seed/seed.js
// Code Generated by Sidekick is for learning and experimentation purposes only.

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const { connectToDatabase } = require('../db');
const products = require('./products.json');

async function seed() {
  console.log('🌱 Starting seed...');

  try {
    const db  = await connectToDatabase();
    const col = db.collection('products');


    // Step 2: Bulk insert
    const result = await col.insertMany(products, { ordered: false });
    console.log(`✅ Inserted ${result.insertedCount} products successfully`);

    // Step 3: Create useful indexes
    await col.createIndex({ id: 1 },       { unique: true });
    await col.createIndex({ category: 1 });
    await col.createIndex({ title: 'text', name: 'text' });
    console.log('✅ Indexes created');

    // Step 4: Verify — print summary by category
    const categories = await col.distinct('category');
    console.log('\n📦 Categories seeded:', categories.join(', '));
    console.log(`\n🎉 Seed complete! ${result.insertedCount} products in MongoDB Atlas (myshop.products)`);

    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
