// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: middleware/verifyGoogleToken.js

const { OAuth2Client } = require('google-auth-library');
const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

const verifyGoogleToken = async (req, res, next) => {
  const authHeader = req.headers.authorization;

  // No token → email-login user, pass through
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return next();
  }

  const token = authHeader.split(' ')[1];

  try {
    // Validates: signature, audience, issuer, expiry
    const ticket = await client.verifyIdToken({
      idToken: token,
      audience: process.env.GOOGLE_CLIENT_ID,
    });
    req.googleUser = ticket.getPayload();
    return next();
  } catch {
    return res.status(401).json({ success: false, message: 'Invalid or expired Google token' });
  }
};

module.exports = verifyGoogleToken;
