// filename: product-card.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { CurrencyPipe, NgClass } from '@angular/common';
import { Component, Input, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Product } from '../../../core/models/product.model';
import { UserListsService } from '../../../services/user-lists.service';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [NgClass, CurrencyPipe, RouterLink],
  templateUrl: './product-card.html',
  styleUrl: './product-card.css',
})
export class ProductCardComponent {
  @Input() product: Product | null = null;
  @Input() skeleton = false;

  lists = inject(UserListsService);

  addToCart(event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
    if (this.product) this.lists.addToCart(this.product, 1);
  }

  toggleWishlist(event: MouseEvent): void {
    event.preventDefault();
    event.stopPropagation();
    if (this.product) this.lists.toggleWishlist(this.product);
  }

  isWishlisted(): boolean {
    return this.product ? this.lists.isInWishlist(this.product.id) : false;
  }

  cartQty(): number {
    return this.product ? this.lists.getCartQuantity(this.product.id) : 0;
  }
}
