// filename: auth.reducer.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { createFeature, createReducer, on } from '@ngrx/store';
import { AppUser } from '../../core/auth/services/auth-service';
import { AuthActions } from './auth.actions';

export interface AuthState {
  user:    AppUser | null;
  token:   string | null;
  loading: boolean;
  error:   string | null;
  sessionRestored:  boolean;
}

const initialState: AuthState = {
  user: null, token: null, loading: false, error: null,
  sessionRestored:  false,
};

export const authFeature = createFeature({
  name: 'auth',
  reducer: createReducer(
    initialState,
    on(AuthActions.restoreSessionSuccess,
      (s, { user, token }) => ({ ...s, user, token, loading: false, sessionRestored: true  })),
    on(AuthActions.restoreSessionFailure,
      (s) => ({ ...s, user: null, token: null, loading: false, sessionRestored: true  })),

    on(AuthActions.loginWithGoogle, AuthActions.loginWithEmail,
      (s) => ({ ...s, loading: true, error: null })),
    on(AuthActions.loginWithGoogleSuccess,
      (s, { user, token }) => ({ ...s, user, token, loading: false })),
    on(AuthActions.loginWithEmailSuccess,
      (s, { user, token }) => ({ ...s, user, token, loading: false })),
    on(AuthActions.loginAsGuestSuccess,
      (s, { user, token }) => ({ ...s, user, token, loading: false })),
    on(AuthActions.loginWithGoogleFailure, AuthActions.loginWithEmailFailure, AuthActions.loginAsGuestFailure,
      (s, { error }) => ({ ...s, loading: false, error })),

    on(AuthActions.logoutSuccess,
      () => ({ ...initialState, sessionRestored: true  })),
  ),
});
