// filename: auth.selectors.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { authFeature } from './auth.reducer';
import { createSelector } from '@ngrx/store';

export const {
  selectUser,
  selectToken,
  selectLoading: selectAuthLoading,
  selectError:   selectAuthError,
  selectSessionRestored
} = authFeature;

export const selectIsLoggedIn = createSelector(
  selectUser, (user) => !!user
);
