// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: auth.effects.ts

import { inject, Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { catchError, from, map, of, switchMap, tap } from 'rxjs';
import { AuthActions } from './auth.actions';
import { AuthService, AppUser } from '../../core/auth/services/auth-service';
import { UserService } from '../../core/auth/services/user.service';

@Injectable()
export class AuthEffects {
  private actions$    = inject(Actions);
  private authService = inject(AuthService);
  private userService = inject(UserService);
  private router      = inject(Router);

  loginWithGoogle$ = createEffect(() =>
    this.actions$.pipe(
      ofType(AuthActions.loginWithGoogle),
      switchMap(({ credential }) =>
        from(this.authService.signInWithGoogle(credential)).pipe(
          map(() => AuthActions.loginWithGoogleSuccess({
            user:  this.authService.user!,
            token: this.authService.token!,
          })),
          catchError((err: Error) =>
            of(AuthActions.loginWithGoogleFailure({ error: err.message }))
          ),
        ),
      ),
    ),
  );

  loginWithEmail$ = createEffect(() =>
    this.actions$.pipe(
      ofType(AuthActions.loginWithEmail),
      switchMap(({ email, password }) =>
        this.userService.loginUser(email, password).pipe(
          switchMap(({ user, token }) =>
            from(this.authService.signInWithEmail(user, token)).pipe(
              map(() => AuthActions.loginWithEmailSuccess({ user, token }))
            )
          ),
          catchError((err) => {
            const message =
              err.status === 404 ? 'User not found'     :
              err.status === 401 ? 'Incorrect password' :
              'Login failed';
            return of(AuthActions.loginWithEmailFailure({ error: message }));
          }),
        ),
      ),
    ),
  );

  loginAsGuest$ = createEffect(() =>
    this.actions$.pipe(
      ofType(AuthActions.loginAsGuest),
      switchMap(({ name, phone }) =>
        this.userService.guestLogin(name, phone).pipe(
          switchMap(({ user, token }) =>
            from(this.authService.signInAsGuest(user, token)).pipe(
              map(() => AuthActions.loginAsGuestSuccess({ user, token }))
            )
          ),
          catchError((err) =>
            of(AuthActions.loginAsGuestFailure({ error: 'Guest login failed' }))
          ),
        ),
      ),
    ),
  );

  redirectAfterLogin$ = createEffect(
    () =>
      this.actions$.pipe(
        ofType(AuthActions.loginWithGoogleSuccess, AuthActions.loginWithEmailSuccess, AuthActions.loginAsGuestSuccess,),
        tap(() => void this.router.navigate(['/home'])),
      ),
    { dispatch: false },
  );

  logout$ = createEffect(() =>
    this.actions$.pipe(
      ofType(AuthActions.logout),
      switchMap(() =>
        from(this.authService.logout()).pipe(
          map(() => AuthActions.logoutSuccess())
        ),
      ),
    ),
  );

  redirectAfterLogout$ = createEffect(
    () =>
      this.actions$.pipe(
        ofType(AuthActions.logoutSuccess),
        tap(() => void this.router.navigate(['/login'])),
      ),
    { dispatch: false },
  );
}
