// filename: home.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { AsyncPipe, NgClass } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { Store } from '@ngrx/store';
import { Header } from '../../../shared/header/header';
import { ErrorMessageComponent } from '../../../shared/ui/error-message/error-message';
import { ProductCardComponent } from '../../../shared/ui/product-card/product-card';
import { UserListsService } from '../../../services/user-lists.service';
import { selectUser } from '../../../store/auth/auth.selectors';
import { ProductsActions } from '../../../store/products/products.actions';
import {
  selectActiveCategory, selectCategories, selectPage, selectProducts,
  selectProductsError, selectProductsLoading, selectSortBy, selectTotal, selectTotalPages,
} from '../../../store/products/products.selectors';
import { Footer } from '../../../shared/footer/footer';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [AsyncPipe, NgClass, Header, ErrorMessageComponent, ProductCardComponent, Footer],
  templateUrl: './home.html',
  styleUrl: './home.css',
})
export class Home implements OnInit {
  private store = inject(Store);
  private lists = inject(UserListsService);

  user$ = this.store.select(selectUser);
  products$ = this.store.select(selectProducts);
  loading$ = this.store.select(selectProductsLoading);
  error$ = this.store.select(selectProductsError);
  categories$ = this.store.select(selectCategories);
  activeCategory$ = this.store.select(selectActiveCategory);
  sortBy$ = this.store.select(selectSortBy);
  page$ = this.store.select(selectPage);
  total$ = this.store.select(selectTotal);
  totalPages$ = this.store.select(selectTotalPages);

  skeletonItems = Array.from({ length: 8 }, (_, i) => i);
  showBanner = signal(true);
  bannerFading = signal(false);

  ngOnInit(): void {
    this.store.dispatch(ProductsActions.loadCategories());
    this.store.dispatch(ProductsActions.loadProducts());
    this.lists.loadAll();
    setTimeout(() => this.bannerFading.set(true), 4000);
    setTimeout(() => this.showBanner.set(false), 4500);
  }

  setCategory(category: string): void { this.store.dispatch(ProductsActions.setCategory({ category })); }
  setSort(sortBy: 'price-asc' | 'price-desc'): void { this.store.dispatch(ProductsActions.setSort({ sortBy })); }
  goToPage(page: number): void { if (page > 0) this.store.dispatch(ProductsActions.setPage({ page })); }
  dismissBanner(): void { this.bannerFading.set(true); setTimeout(() => this.showBanner.set(false), 500); }
  showBannerAgain(): void { this.bannerFading.set(false); this.showBanner.set(true); }
}
