// filename: home.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import {
  ChangeDetectionStrategy, Component,
  OnDestroy, OnInit, inject, signal, PLATFORM_ID,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { TitleCasePipe, AsyncPipe, NgClass } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Store } from '@ngrx/store';
import { Subject, takeUntil } from 'rxjs';
import { Header } from '../../../shared/header/header';
import { ErrorMessageComponent } from '../../../shared/ui/error-message/error-message';
import { ProductCardComponent } from '../../../shared/ui/product-card/product-card';
import { UserListsService } from '../../../services/user-lists.service';
import { selectUser } from '../../../store/auth/auth.selectors';
import { ProductsActions } from '../../../store/products/products.actions';
import {
  selectActiveCategory, selectCategories, selectHasMore,
  selectLoadingMore, selectProducts, selectProductsError,
  selectProductsLoading, selectSortBy, selectTotal,
} from '../../../store/products/products.selectors';
import { Footer } from '../../../shared/footer/footer';

@Component({
  selector: 'app-home',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    TitleCasePipe, AsyncPipe, NgClass, RouterLink,
    Header, ErrorMessageComponent, ProductCardComponent, Footer,
  ],
  templateUrl: './home.html',
  styleUrl:    './home.css',
})
export class Home implements OnInit, OnDestroy {
  private store      = inject(Store);
  private lists      = inject(UserListsService);
  private platformId = inject(PLATFORM_ID);
  private destroy$   = new Subject<void>();
  private observer!: IntersectionObserver;

  user$           = this.store.select(selectUser);
  products$       = this.store.select(selectProducts);
  loading$        = this.store.select(selectProductsLoading);
  loadingMore$    = this.store.select(selectLoadingMore);
  hasMore$        = this.store.select(selectHasMore);
  error$          = this.store.select(selectProductsError);
  categories$     = this.store.select(selectCategories);
  activeCategory$ = this.store.select(selectActiveCategory);
  sortBy$         = this.store.select(selectSortBy);
  total$          = this.store.select(selectTotal);

  skeletonItems = Array.from({ length: 8 }, (_, i) => i);
  showBanner    = signal(true);
  bannerFading  = signal(false);

  ngOnInit(): void {
    this.store.dispatch(ProductsActions.loadCategories());
    this.store.dispatch(ProductsActions.loadProducts());
    this.lists.loadAll();

    setTimeout(() => this.bannerFading.set(true), 4000);
    setTimeout(() => this.showBanner.set(false), 4500);

    // ✅ Attach observer AFTER products arrive (sentinel is always in DOM)
    if (isPlatformBrowser(this.platformId)) {
      this.products$
        .pipe(takeUntil(this.destroy$))
        .subscribe((products) => {
          if (products.length > 0) {
            this.attachObserver();
          }
        });
    }
  }

  private attachObserver(): void {
    // Only attach once
    if (this.observer) return;

    const sentinel = document.getElementById('scroll-sentinel');
    if (!sentinel) return;

    this.observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          this.store.dispatch(ProductsActions.loadMoreProducts());
        }
      },
      {
        root:       null,    // whole viewport
        rootMargin: '300px', // trigger 300px before sentinel is visible
        threshold:  0,
      }
    );

    this.observer.observe(sentinel);
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
    this.destroy$.next();
    this.destroy$.complete();
  }

  setCategory(category: string): void {
    // Reset observer so it re-attaches after new products load
    this.observer?.disconnect();
    this.observer = null!;
    this.store.dispatch(ProductsActions.setCategory({ category }));
  }

  setSort(sortBy: 'price-asc' | 'price-desc'): void {
    this.observer?.disconnect();
    this.observer = null!;
    this.store.dispatch(ProductsActions.setSort({ sortBy }));
  }

  dismissBanner(): void {
    this.bannerFading.set(true);
    setTimeout(() => this.showBanner.set(false), 500);
  }
  showBannerAgain(): void {
    this.bannerFading.set(false);
    this.showBanner.set(true);
  }
}
