// filename: about.spec.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { ComponentFixture, TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { provideMockStore } from '@ngrx/store/testing';


// ✅ FIX: import ToastrModule — provides ToastrService + ToastConfig to TestBed
import { ToastrModule } from 'ngx-toastr';

import { AboutComponent } from './about';

describe('AboutComponent', () => {

  let fixture: ComponentFixture<AboutComponent>;
  let component: AboutComponent;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [
        AboutComponent,
        RouterTestingModule,
        ToastrModule.forRoot(), // ✅ THE FIX: registers ToastrService + ToastConfig
                                // forRoot() is required — same as in your AppModule
                                // without it, ToastConfig token is never registered
      ],
      providers: [
        provideMockStore({ initialState: {} }), // from previous fix — keep this
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(AboutComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  // ── BLOCK 1: Component Creation ───────────────────────────────────────────
  it('should create the component', () => {
    expect(component).toBeTruthy();
  });

  // ── BLOCK 2: Static Data ──────────────────────────────────────────────────
  it('should have exactly 6 stats', () => {
    expect(component.stats.length).toBe(6);
  });

  it('every stat should have a label and a value', () => {
    component.stats.forEach(stat => {
      expect(stat.label).toBeTruthy();
      expect(stat.value).toBeTruthy();
    });
  });

  it('should have exactly 6 core values', () => {
    expect(component.values.length).toBe(6);
  });

  it('every core value should have icon, title and desc', () => {
    component.values.forEach(v => {
      expect(v.icon).toBeTruthy();
      expect(v.title).toBeTruthy();
      expect(v.desc).toBeTruthy();
    });
  });

  it('should have exactly 6 milestones', () => {
    expect(component.milestones.length).toBe(6);
  });

  it('every milestone should have a year, title and desc', () => {
    component.milestones.forEach(m => {
      expect(m.year).toBeTruthy();
      expect(m.title).toBeTruthy();
      expect(m.desc).toBeTruthy();
    });
  });

  it('should have exactly 6 team members', () => {
    expect(component.team.length).toBe(6);
  });

  it('every team member should have name, role, avatar and bio', () => {
    component.team.forEach(member => {
      expect(member.name).toBeTruthy();
      expect(member.role).toBeTruthy();
      expect(member.avatar).toBeTruthy();
      expect(member.bio).toBeTruthy();
    });
  });

  it('should have at least 4 FAQs', () => {
    expect(component.faqs.length).toBeGreaterThanOrEqual(4);
  });

  it('every FAQ should have a question and an answer', () => {
    component.faqs.forEach(faq => {
      expect(faq.q).toBeTruthy();
      expect(faq.a).toBeTruthy();
    });
  });

  // ── BLOCK 3: FAQ Toggle Logic ─────────────────────────────────────────────
  it('openFaqIndex should be null on initialisation', () => {
    expect(component.openFaqIndex).toBeNull();
  });

  it('toggleFaq(0) should open FAQ at index 0', () => {
    component.toggleFaq(0);
    expect(component.openFaqIndex).toBe(0);
  });

  it('toggleFaq(0) called twice should close it (back to null)', () => {
    component.toggleFaq(0);
    component.toggleFaq(0);
    expect(component.openFaqIndex).toBeNull();
  });

  it('toggleFaq should switch from one FAQ to another', () => {
    component.toggleFaq(0);
    component.toggleFaq(3);
    expect(component.openFaqIndex).toBe(3);
  });

  it('toggleFaq should work for the last FAQ in the list', () => {
    const lastIndex = component.faqs.length - 1;
    component.toggleFaq(lastIndex);
    expect(component.openFaqIndex).toBe(lastIndex);
  });

  // ── BLOCK 4: DOM Tests ────────────────────────────────────────────────────
  it('should render the page heading eSHOPPERS', () => {
    const el: HTMLElement = fixture.nativeElement;
    expect(el.textContent).toContain('eSHOPPERS');
  });

  it('should render the correct number of stat cards', () => {
    const el: HTMLElement = fixture.nativeElement;
    const statCards = el.querySelectorAll('[data-testid="stat-card"]');
    expect(statCards.length).toBe(6);
  });

  it('should render the correct number of value cards', () => {
    const el: HTMLElement = fixture.nativeElement;
    const valueCards = el.querySelectorAll('[data-testid="value-card"]');
    expect(valueCards.length).toBe(6);
  });

  it('should NOT show FAQ answer before it is toggled', () => {
    const el: HTMLElement = fixture.nativeElement;
    const answer = el.querySelector('[data-testid="faq-answer-0"]');
    expect(answer).toBeNull();
  });

  it('should show FAQ answer in DOM after toggleFaq is called', () => {
    component.toggleFaq(0);
    fixture.detectChanges();
    const el: HTMLElement = fixture.nativeElement;
    const answer = el.querySelector('[data-testid="faq-answer-0"]');
    expect(answer).not.toBeNull();
  });

   it('should hide FAQ answer again after toggling closed', () => {
    component.toggleFaq(0);   // open  ─┐ no detectChanges
    component.toggleFaq(0);   // close ─┘ between these two

    fixture.detectChanges();  // ONE detectChanges at end — sees final closed state only

    const el: HTMLElement = fixture.nativeElement;
    expect(el.querySelector('[data-testid="faq-answer-0"]')).toBeNull();
  });

  it('should render the Start Shopping button', () => {
    const el: HTMLElement = fixture.nativeElement;
    const btn = el.querySelector('[data-testid="shop-btn"]');
    expect(btn).not.toBeNull();
    expect(btn?.textContent?.trim()).toBe('Start Shopping');
  });

});
