// filename: app.state.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { AuthState } from './auth/auth.reducer';
import { ProductsState } from './products/products.reducer';

export interface AppState {
  auth: AuthState;
  products: ProductsState;
}
