// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: cart.ts

import { CurrencyPipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { UserListsService } from '../../../services/user-lists.service';
import { Header } from '../../../shared/header/header';
import { Footer } from '../../../shared/footer/footer';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [Header, RouterLink, CurrencyPipe, Footer],
  templateUrl: './cart.html',
})
export class CartComponent implements OnInit {
  lists         = inject(UserListsService);
  private router = inject(Router);

  ngOnInit(): void { this.lists.loadAll(); }

  increase(productId: number, quantity: number): void {
    this.lists.updateCart(productId, quantity + 1);
  }

  decrease(productId: number, quantity: number): void {
    if (quantity <= 1) { this.lists.removeFromCart(productId); return; }
    this.lists.updateCart(productId, quantity - 1);
  }

  remove(productId: number): void {
    this.lists.removeFromCart(productId);
  }

  totalAmount(): number {
    return this.lists.cartItems().reduce((sum, item) => sum + item.price * item.quantity, 0);
  }

  proceedToCheckout(): void {
    this.router.navigate(['/checkout']);   // ← just navigate, no Stripe call here
  }
}
