// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: payment.service.ts

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';
import { CartItem } from './user-lists.service';

interface CreateIntentResponse {
  success:      boolean;
  clientSecret: string;
}

@Injectable({ providedIn: 'root' })
export class PaymentService {
  private http   = inject(HttpClient);
  private apiUrl = `${environment.apiUrl}/payments`;

  createIntent(amount: number, items: CartItem[]): Observable<CreateIntentResponse> {
    return this.http.post<CreateIntentResponse>(
      `${this.apiUrl}/create-intent`,
      { amount, items }
    );
  }
}
