// filename: product.service.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';
import {
  CategoriesResponse,
  ProductResponse,
  ProductsResponse,
} from '../core/models/product.model';

export interface ProductQuery {
  search?: string;
  category?: string;
  sort?: 'price-asc' | 'price-desc';
  page?: number;
  pageSize?: number;
}

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private http = inject(HttpClient);
  private apiUrl = `${environment.apiUrl}/products`;

  getProducts(query: ProductQuery = {}): Observable<ProductsResponse> {
    let params = new HttpParams();

    if (query.search?.trim()) {
      params = params.set('search', query.search.trim());
    }

    if (query.category?.trim() && query.category !== 'All') {
      params = params.set('category', query.category);
    }

    if (query.sort) {
      params = params.set('sort', query.sort);
    }

    if (query.page != null) {
      params = params.set('page', query.page);
    }

    if (query.pageSize != null) {
      params = params.set('pageSize', query.pageSize);
    }

    return this.http.get<ProductsResponse>(this.apiUrl, { params });
  }

  getCategories(): Observable<CategoriesResponse> {
    return this.http.get<CategoriesResponse>(`${this.apiUrl}/categories`);
  }

  getProductById(id: number): Observable<ProductResponse> {
    return this.http.get<ProductResponse>(`${this.apiUrl}/${id}`);
  }
}
