// filename: user-lists.service.spec.ts
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { TestBed }                     from '@angular/core/testing';
import { HttpClientTestingModule,
         HttpTestingController }       from '@angular/common/http/testing';
import { vi }                          from 'vitest';
import { UserListsService, CartItem }  from './user-lists.service';
import { AuthService }                 from '../core/auth/services/auth-service';
import { ToastrService }               from 'ngx-toastr';
import { Product }                     from '../core/models/product.model';
import { environment }                 from '../../environments/environment';

// ─── Test data ────────────────────────────────────────────────────────────────

const API = environment.apiUrl;
const UID = 'user-123';

const mockProduct: Product = {
  id: 1, title: 'Headphones', name: 'Headphones', description: '',
  price: 49.99, category: 'Electronics', image: '', thumbnail: '',
  rating: 4, stock: 5,
};

const mockCartItem: CartItem = {
  productId: 1, quantity: 2, name: 'Headphones',
  price: 49.99, thumbnail: '', stock: 5,
};

// ─────────────────────────────────────────────────────────────────────────────

describe('UserListsService — minimal', () => {
  let service:   UserListsService;
  let httpMock:  HttpTestingController;
  let mockToastr: { success: any; error: any; warning: any; info: any };

  beforeEach(async () => {
    mockToastr = {
      success: vi.fn(), error: vi.fn(),
      warning: vi.fn(), info:  vi.fn(),
    };

    await TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        UserListsService,
        { provide: AuthService,   useValue: { user: { sub: UID } } },
        { provide: ToastrService, useValue: mockToastr },
      ],
    }).compileComponents();

    service  = TestBed.inject(UserListsService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();          // fails if any HTTP call was made but never flushed
    TestBed.resetTestingModule(); 
  });

  // ── 1. Service exists ─────────────────────────────────────────────────────
  it('should create', () => {
    expect(service).toBeTruthy();
  });

  // ── 2. Signals start empty ────────────────────────────────────────────────
  it('cartItems and wishlistIds should start empty', () => {
    expect(service.cartItems()).toEqual([]);
    expect(service.wishlistIds()).toEqual([]);
  });

  // ── 3. Computed signals ───────────────────────────────────────────────────
  it('cartCount should sum item quantities', () => {
    service.cartItems.set([
      { ...mockCartItem, quantity: 3 },
      { ...mockCartItem, productId: 2, quantity: 2 },
    ]);
    expect(service.cartCount()).toBe(5);
  });

  it('wishlistCount should equal number of ids', () => {
    service.wishlistIds.set([1, 2, 3]);
    expect(service.wishlistCount()).toBe(3);
  });

  // ── 4. isInWishlist() ─────────────────────────────────────────────────────
  it('isInWishlist() should return true when id is present', () => {
    service.wishlistIds.set([1]);
    expect(service.isInWishlist(1)).toBe(true);
  });

  it('isInWishlist() should return false when id is absent', () => {
    expect(service.isInWishlist(99)).toBe(false);
  });

  // ── 5. getCartQuantity() ──────────────────────────────────────────────────
  it('getCartQuantity() should return quantity for item in cart', () => {
    service.cartItems.set([{ ...mockCartItem, quantity: 3 }]);
    expect(service.getCartQuantity(1)).toBe(3);
  });

  it('getCartQuantity() should return 0 when item not in cart', () => {
    expect(service.getCartQuantity(99)).toBe(0);
  });

  // ── 6. loadAll() ──────────────────────────────────────────────────────────
  it('loadAll() should populate signals on success', () => {
    service.loadAll();

    httpMock.expectOne(`${API}/cart/${UID}`)
            .flush({ success: true, items: [mockCartItem] });
    httpMock.expectOne(`${API}/wishlist/${UID}`)
            .flush({ success: true, productIds: [1], products: [] });

    expect(service.cartItems()).toEqual([mockCartItem]);
    expect(service.wishlistIds()).toEqual([1]);
  });

  it('loadAll() should reset signals to [] on error', () => {
    service.cartItems.set([mockCartItem]);

    service.loadAll();

    httpMock.expectOne(`${API}/cart/${UID}`)
            .flush('err', { status: 500, statusText: 'Error' });
    httpMock.match(`${API}/wishlist/${UID}`);   // drain leftover request

    expect(service.cartItems()).toEqual([]);
    expect(service.wishlistIds()).toEqual([]);
  });

  // ── 7. addToCart() ────────────────────────────────────────────────────────
  it('addToCart() should POST and update cartItems', () => {
    service.addToCart(mockProduct, 1);

    const req = httpMock.expectOne(`${API}/cart/${UID}`);
    expect(req.request.method).toBe('POST');
    expect(req.request.body).toEqual({ productId: 1, quantity: 1 });

    req.flush({ success: true, items: [mockCartItem] });

    expect(service.cartItems()).toEqual([mockCartItem]);
    expect(mockToastr.success).toHaveBeenCalled();
  });

  it('addToCart() should call toastr.error on failure', () => {
    service.addToCart(mockProduct);
    httpMock.expectOne(`${API}/cart/${UID}`)
            .flush('err', { status: 500, statusText: 'Error' });
    expect(mockToastr.error).toHaveBeenCalledWith('Failed to add to cart');
  });

  // ── 8. updateCart() ───────────────────────────────────────────────────────
  it('updateCart() should PATCH the correct URL', () => {
    service.updateCart(1, 3);

    const req = httpMock.expectOne(`${API}/cart/${UID}/1`);
    expect(req.request.method).toBe('PATCH');
    expect(req.request.body).toEqual({ quantity: 3 });
    req.flush({ success: true, items: [] });
  });

  // ── 9. removeFromCart() ───────────────────────────────────────────────────
  it('removeFromCart() should DELETE and clear cartItems', () => {
    service.cartItems.set([mockCartItem]);
    service.removeFromCart(1);

    httpMock.expectOne(`${API}/cart/${UID}/1`)
            .flush({ success: true, items: [] });

    expect(service.cartItems()).toEqual([]);
    expect(mockToastr.warning).toHaveBeenCalled();
  });

  // ── 10. toggleWishlist() — add ────────────────────────────────────────────
  it('toggleWishlist() should POST when product not in wishlist', () => {
    service.wishlistIds.set([]);
    service.toggleWishlist(mockProduct);

    const req = httpMock.expectOne(`${API}/wishlist/${UID}`);
    expect(req.request.method).toBe('POST');
    req.flush({ success: true, productIds: [1], products: [] });

    expect(service.wishlistIds()).toEqual([1]);
    expect(mockToastr.success).toHaveBeenCalled();
  });

  // ── 11. toggleWishlist() — remove ─────────────────────────────────────────
  it('toggleWishlist() should DELETE when product already in wishlist', () => {
    service.wishlistIds.set([1]);
    service.toggleWishlist(mockProduct);

    const req = httpMock.expectOne(`${API}/wishlist/${UID}/1`);
    expect(req.request.method).toBe('DELETE');
    req.flush({ success: true, productIds: [], products: [] });

    expect(service.wishlistIds()).toEqual([]);
    expect(mockToastr.warning).toHaveBeenCalled();
  });

  // ── 12. clearCart() ───────────────────────────────────────────────────────
  it('clearCart() should reset cartItems immediately and DELETE', () => {
    service.cartItems.set([mockCartItem]);
    service.clearCart();

    expect(service.cartItems()).toEqual([]);   // sync — before flush

    httpMock.expectOne(`${API}/cart/${UID}`).flush({});
  });

  // ── 13. clear() ───────────────────────────────────────────────────────────
  it('clear() should reset both signals with no HTTP call', () => {
    service.cartItems.set([mockCartItem]);
    service.wishlistIds.set([1]);

    service.clear();

    expect(service.cartItems()).toEqual([]);
    expect(service.wishlistIds()).toEqual([]);
  });
});
