// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: auth-interceptor.ts

import { HttpInterceptorFn } from '@angular/common/http';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { Store } from '@ngrx/store';
import { AuthService } from '../services/auth-service';
import { AuthActions } from '../../../store/auth/auth.actions';

export const authInterceptor: HttpInterceptorFn = (req, next) => {
  const authService = inject(AuthService);
  const router      = inject(Router);
  const store       = inject(Store);

  if (req.url.includes('accounts.google.com')) {
    return next(req);
  }

  if (!authService.token) {
    return next(req);
  }

  const authReq = req.clone({
    setHeaders: { Authorization: `Bearer ${authService.token}` },
  });

  console.log('[Interceptor] Token attached for:', req.url);

  return next(authReq).pipe(
    catchError(err => {
      if (err.status === 401) {
        console.warn('[Interceptor] 401 received — forcing logout');
        store.dispatch(AuthActions.logout());
        void router.navigate(['/login']);
      }
      return throwError(() => err);
    })
  );
};
